# Leaf-folder Terraform for orbit/dev/ca-central-1.
#
# provider.tf, backend.tf and versions.tf are GENERATED by root.hcl - do not
# create them here. This file only wires modules together for this one account.

module "network" {
  source = "../../../../../modules/network"

  environment = var.environment
  project     = var.project
  cidr_block  = "10.10.0.0/16"
}

module "dns" {
  source = "../../../../../modules/dns"

  # Records go into the hosted zone that lives in the *networking* account,
  # so we hand this module the aliased cross-account provider.
  providers = {
    aws = aws.networking_account
  }

  hosted_zone_id = var.hosted_zone_id
  record_name    = var.domain_name
  record_type    = "A"
  record_values  = ["203.0.113.10"] # TEST-NET-3 placeholder
}
